name: Respin RDX
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - 'leiame.md'
      - 'license'
      - 'readme.md'
      - 'to-do.log'
      - '*.jpg'
      - '*.png'
      - '*.svg'
      - 'site/**'
      - 'site-deploy.ps1'
  schedule:
    - cron:  '0 */12 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    #container: debian:bookworm
    steps:
      - uses: actions/checkout@v4
      - name: Respin RDX build
        run: bash scripts/build.sh
      - name: MEGA upload
        uses: Mamami-Digital/action-megacmd@master
        with:
          args: put -c ./respin-rdx*.iso /respin-rdx/
        env:
          USERNAME: ${{ secrets.MEGA_USERNAME }}
          PASSWORD: ${{ secrets.MEGA_PASSWORD }}
      - name: Send email
        uses: devellany/send-mailer@v1.0.2
        with:
          host: disroot.org
          port: 587
          account: ${{secrets.MAIL_ADDRESS}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: github-actions.rauldipeas@lock.email
          from: ${{secrets.MAIL_ADDRESS}}
          to: ${{secrets.MAIL_ADDRESS}}
          subject: Respin RDX actions report
          body: A GitHub Action run has completed
          contentType: text/plain
          #attachments: '[{"path":"README.md"}]'
      - name: SFTP upload
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: rauldipeas
          server: frs.sourceforge.net
          port: 22
          local_path: './respin-rdx*.iso'
          remote_path: '/home/pfs/project/respin-rdx'
          sftp_only: true
          ssh_private_key: ''
          password: ${{ secrets.SFTP_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          name: respin-rdx
          path: ./respin-rdx*.iso
      - uses: otto-de/purge-deprecated-workflow-runs@v2
        with:
          remove-cancelled: true
          remove-failed: true
          remove-obsolete: true
          token: ${{ secrets.PAT }}
          #remove-older-than: 7d